name: Run all autotests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Select tests to run
        required: true
        type: choice
        default: 'all'
        options:
          - all
          - not_slow
          - smoke
          - regression

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Python API and UI QA autotests
    steps: 
      - name: Copy source code
        uses: actions/checkout@v4
      - name: Set up python env
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install Playwright browsers
        run: playwright install --with-deps
      - name: Run not slow tests
        if: github.event.inputs.deployment_target == 'not_slow'
        run: pytest -v -s -rxXs --tracing=retain-on-failure -m "not slow"
      - name: Run smoke tests
        if: github.event.inputs.deployment_target == 'smoke'
        run: pytest -v -s -rxXs --tracing=retain-on-failure -m "smoke"
      - name: Run regression tests
        if: github.event.inputs.deployment_target == 'regression'
        run: pytest -v -s -rxXs --tracing=retain-on-failure -m "regression"
      - name: Run all tests
        run: pytest -v -s -rxXs --tracing=retain-on-failure
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-traces
          path: test-results/
  
  