name: Run all autotests


on:
  workflow_dispatch:
    inputs:
      deployment_targe:
        description: select tests to run
        required: true
        type: choise
        default: all
        options:
          - all

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: QA tests
    steps: 
      - name: Copy source code
        uses: actions/checkout@v4
      - name: Set up python env
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest -v -s -rxXs
